routes/web.php
<?php

use App\Http\Controllers\CourseController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TempahanKenderaanController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 *
 * get
 * post
 * any
 * match []
 * delete
 * d
 */
Route::get('/', function(){
    return redirect('/login');
});

Route::get('tempahan-kenderaan', [TempahanKenderaanController::class, 'index']);
Route::match(['get','post'], 'tempahan-kenderaan2', [TempahanKenderaanController::class, 'index']);

/**
 * Route Student
 */
Route::middleware('auth')->group(function(){
    Route::prefix('student')->as('student.')->group(function(){
        Route::get('/',[StudentController::class, 'index'])->name('index')
        ->middleware('role:superadmin');
        Route::get('/create',[StudentController::class, 'create'])->name('create');
        Route::get('/show/{id}',[StudentController::class, 'show'])->name('show');
        Route::get('/edit/{id}',[StudentController::class, 'edit'])->name('edit');

        Route::post('/store',[StudentController::class, 'store'])->name('store');
        Route::post('/update/{id}',[StudentController::class, 'update'])->name('update');
    });

    Route::prefix('course')->as('course.')->group(function(){
        Route::get('/', [CourseController::class, 'index'])->name('index');
        Route::get('/show/{id}',[CourseController::class, 'show'])->name('show');
        Route::get('/edit/{id}',[CourseController::class, 'edit'])->name('edit');

        Route::post('/update/{id}',[CourseController::class, 'update'])->name('update');
    });

    Route::prefix('user')->as('user.')->group(function(){
        Route::get('/', [UserController::class, 'index'])->name('index');
        Route::get('/create', [UserController::class, 'create'])->name('create');
        Route::post('/store', [UserController::class, 'store'])->name('store');
        Route::get('/delete/{id}', [UserController::class, 'destroy'])->name('delete');
    });
});



// Route::middleware('auth')->group(function(){
//     Route::prefix('student')->group(function(){
//         Route::get('/',[StudentController::class, 'index']);
//         Route::get('/create',[StudentController::class, 'create']);
//         Route::get('/show/{id}',[StudentController::class, 'show']);
//         Route::get('/edit/{id}',[StudentController::class, 'edit']);

//         Route::post('/store',[StudentController::class, 'store'])
//         ->name('student.store');
//         Route::post('/update/{id}',[StudentController::class, 'update']);
//     });
// });

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;

    public function course(){
        $this->belongsTo(Course::class, 'course_id', 'id');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $students = Student::all();
        return view('student.index', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('student.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // return $request->url; // certain object
        // dd($request->all()); // semua object dalm form

        return redirect()->route('student.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        return 'show ui ' .$id;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        return view('student.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        return $request->name .' for student ID ' .$id;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function camelCase($id){
        $primary_school = 'spm'; // snake_case
        $primarySchool_grade = ''; //camel + snake case
        $camelCase = '';  // camel case
    }
}

resources/views/student/create.blade.php
@extends('app')

@section('content')
<form action="{{ route('student.store') }}" class="" method="post">
    @csrf
    <label>Nama</label>
    <input type="text" name="name">
    <input type="text" name="url" value="{{ route('student.store') }}">

    <button type="submit">Hantar/Submit</button>
</form>
@endsection

resources/views/student/edit.blade.php
<html>
    <body>
        <form action="{{ url('/student/update/NDP0001') }}" class="" method="post">
            @csrf
            <label>Nama</label>
            <input type="text" name="name" value="sakinah">

            <button type="submit">Kemaskini</button>
        </form>
    </body>
</html>

resources/views/student/index.blade.php
@extends('app')

@section('content')
    <!-- Page Title -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">List Students </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Student</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Page Content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">List Students</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>NDP</th>
                                        <th>Name</th>
                                        <th>Nric</th>
                                        <th>Tel No</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($students as $s)
                                        <tr>
                                            <td>{{ $s->ndp }}</td>
                                            <td>{{ $s->name }}</td>
                                            <td>{{ $s->ic }}</td>
                                            <td>{{ ($s->tel_no) ? $s->tel_no : '-' }}</td>
                                            <td>
                                                <a href="{{ route('student.show', $s->id) }}" class="btn btn-primary">Show</a>
                                                <a href="{{ route('student.edit', $s->id) }}" class="btn btn-info">Edit</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>NDP</th>
                                        <th>Name</th>
                                        <th>Nric</th>
                                        <th>Tel No</th>
                                        <th>Actions</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('script')
@endsection