routes/web.php
<?php

use App\Http\Controllers\CourseController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TempahanKenderaanController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 *
 * get
 * post
 * any
 * match []
 * delete
 * d
 */
Route::get('/', function(){
    return redirect('/login');
});

Route::get('tempahan-kenderaan', [TempahanKenderaanController::class, 'index']);
Route::match(['get','post'], 'tempahan-kenderaan2', [TempahanKenderaanController::class, 'index']);

/**
 * Route Student
 */
Route::middleware('auth')->group(function(){
    Route::prefix('student')->as('student.')->group(function(){
        Route::get('/',[StudentController::class, 'index'])->name('index')
        ->middleware('role:superadmin');
        Route::get('/create',[StudentController::class, 'create'])->name('create');
        Route::get('/show/{id}',[StudentController::class, 'show'])->name('show');
        Route::get('/edit/{id}',[StudentController::class, 'edit'])->name('edit');

        Route::post('/store',[StudentController::class, 'store'])->name('store');
        Route::post('/update/{id}',[StudentController::class, 'update'])->name('update');
    });

    Route::prefix('course')->as('course.')->group(function(){
        Route::get('/', [CourseController::class, 'index'])->name('index');
        Route::get('/show/{id}',[CourseController::class, 'show'])->name('show');
        Route::get('/edit/{id}',[CourseController::class, 'edit'])->name('edit');

        Route::post('/update/{id}',[CourseController::class, 'update'])->name('update');
    });

    Route::prefix('user')->as('user.')->group(function(){
        Route::get('/', [UserController::class, 'index'])->name('index');
        Route::get('/create', [UserController::class, 'create'])->name('create');
        Route::post('/store', [UserController::class, 'store'])->name('store');
        Route::get('/delete/{id}', [UserController::class, 'destroy'])->name('delete');
    });
});



// Route::middleware('auth')->group(function(){
//     Route::prefix('student')->group(function(){
//         Route::get('/',[StudentController::class, 'index']);
//         Route::get('/create',[StudentController::class, 'create']);
//         Route::get('/show/{id}',[StudentController::class, 'show']);
//         Route::get('/edit/{id}',[StudentController::class, 'edit']);

//         Route::post('/store',[StudentController::class, 'store'])
//         ->name('student.store');
//         Route::post('/update/{id}',[StudentController::class, 'update']);
//     });
// });

app/Models/Course.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    use HasFactory;

    protected $table = "courses";
    protected $primaryKey = 'id';

    // public $incrementing  = false;

    protected $fillable = [
        "id",
        "code",
        "name",
        "is_active",
        "created_at",
        "updated_at"
    ];

    public function students(){
        return $this->hasMany(Student::class);
    }
}

app/Http/Controllers/CourseController.php
<?php

namespace App\Http\Controllers;

use App\Models\Course;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class CourseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $user = Auth::user();
        // return $user;
        $courses = Course::all();
        $courses = Course::orderBy('created_at', 'asc')->get();

        $courses = DB::table('courses')->where('is_Active', 1)->get();
        // $courses  = Course::where('name', 'Algorithm')->orWhere('is_active', 0)->get();

        $courses = Course::with('students')->get();
        return view('course.index', compact('courses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $course = new Course();
        $course->name = 'physic';
        $course->code = 'FTP51';
        $course->save();

        $course = Course::create([
            'name' => 'English',
            'code' => 'EN1234'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $course = Course::find($id);
        return view('course.show', compact('course'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $course = Course::find($id);
        return view('course.edit', compact('course'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $cource = Course::find($id);
        $cource->name = $request->name;
        $cource->is_active = 1;
        $cource->save();

        return redirect()->route('course.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $course = Course::find($id);
        $course->delete();
    }
}

resources/views/course/edit.blade.php
@extends('app')

@section('content')
<form method="post" action="{{ route('course.update', $course->id) }}">
    @csrf

    <input type="text" name="name" value="{{ $course->name }}">
    <button type="submit">Update</button>
</form>
@endsection

resources/views/course/index.blade.php
@extends('app')

@section('content')
<!-- Page Title -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                Courses
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Courses</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Page Content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">List Courses</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Code</th>
                                    <th>Name</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($courses as $c)
                                <tr>
                                    <td>{{ $c->id }}</td>
                                    <td>{{ $c->code }}</td>
                                    <td>{{ $c->name }}</td>
                                    <td>
                                        @if($c->is_active == 1)
                                            <span class="badge badge-success">Active</span>
                                        @else
                                            <span class="badge badge-danger">Inactive</span>
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{ route('course.show', $c->id) }}" class="btn btn-primary">Show</a>
                                        <a href="{{ route('course.edit', $c->id) }}" class="btn btn-info">Edit</a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Code</th>
                                    <th>Name</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/course/show.blade.php
@extends('app')

@section('content')
{{ $course->id }} <br>
{{ $course->name }} <br>
@endsection